version: '3.1'
services:
  db:
    hostname: mysql
    image: mysql:8.0.23
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "bs23@banksystem"
    ports:
      - 7779:3306
  adminer:
    hostname: mysql
    image: adminer
    restart: always
    ports:
      - 8587:8080
    depends_on:
      - db
  bank23-system:
    image: dokerid977/bank23-system:2.0
    restart: always
    ports:
      - 9091:7077
    environment:
      - DB_CONNECTION_IP=db
      - DB_CONNECTION_USERNAME=root
      - DB_CONNECTION_PASSWORD=bs23@banksystem
    depends_on:
      - db


volumes:
  db-data: